title: Audiotarky | Blog
description: >
  Audiotarky (Audio Autarky) is a new streaming platform, focussed on paying musicians directly & clearly for all the music they create.
baseurl: ""
url: "https://audiotarky.com"
twitter_username: audiotarky
github_username:  audiotarky
ilp: "$ilp.uphold.com/WRPFhabhyrxF"
exclude:
 - CNAME
 - makepost.py
 - venv
permalink: /:year/:month/:day/:title/index.html
highlighter: rouge